const DEFAULT_SETTINGS = {
  reels: {
    youtube: true,
    tiktok: true,
    instagram: true,
    facebook: true
  },
  adult: {
    master: true
  },
  doomscroll: {
    threshold: 7,
    cooldownMinutes: 15,
    resetGapSeconds: 90
  }
};

const ADULT_DOMAINS = [
  "4tube.asia", "4tube.be", "4tube.bid", "4tube.bond",
  "4tube.casa", "4tube.co", "4tube.com", "4tube.hu",
  "4tube.icu", "4tube.info", "4tube.stream", "8muses.com",
  "8muses.info", "8muses.io", "8muses.link", "8muses.pro",
  "8muses.red", "8muses.ru", "8muses.xxx", "adultfriendfinder.co",
  "adultfriendfinder.com", "adultfriendfinder.eu", "adultfriendfinder.hk", "adultfriendfinder.hu",
  "adultfriendfinder.it", "adultfriendfinder.lt", "adultfriendfinder.ltd", "adultfriendfinder.nl",
  "adultfriendfinder.tv", "adultfriendfinder.uk", "alphaporno.co", "alphaporno.com",
  "analdin.asia", "analdin.bid", "analdin.com", "analdin.live",
  "analdin.xxx", "anyporn.asia", "anyporn.buzz", "anyporn.co",
  "anyporn.com", "anyporn.de", "anyporn.fun", "anyporn.info",
  "anyporn.ink", "anyporn.lol", "anyporn.mom", "anyporn.online",
  "anyporn.org", "anyporn.quest", "anyporn.space", "anyporn.tv",
  "anyporn.video", "anyporn.xxx", "anyporn.yachts", "ashemaletube.co",
  "ashemaletube.com", "ashemaletube.dev", "ashemaletube.icu", "ashemaletube.me",
  "ashemaletube.name", "ashemaletube.nl", "ashemaletube.tv", "beeg.asia",
  "beeg.be", "beeg.casa", "beeg.cfd", "beeg.co",
  "beeg.com", "beeg.day", "beeg.diy", "beeg.faith",
  "beeg.family", "beeg.fun", "beeg.gg", "beeg.homes",
  "beeg.hu", "beeg.icu", "beeg.ink", "beeg.link",
  "beeg.ltd", "beeg.men", "beeg.onl", "beeg.online",
  "beeg.party", "beeg.pl", "beeg.porn", "beeg.press",
  "beeg.quest", "beeg.red", "beeg.sex", "beeg.social",
  "beeg.space", "beeg.team", "beeg.tv", "beeg.win",
  "beeg.work", "beeg.works", "beeg.world", "beeg.wtf",
  "beeg.xxx", "bongacams.at", "bongacams.be", "bongacams.bz",
  "bongacams.cam", "bongacams.ch", "bongacams.cl", "bongacams.com",
  "bongacams.dk", "bongacams.ee", "bongacams.es", "bongacams.eu",
  "bongacams.fi", "bongacams.fr", "bongacams.gratis", "bongacams.info",
  "bongacams.it", "bongacams.li", "bongacams.lt", "bongacams.lu",
  "bongacams.lv", "bongacams.me", "bongacams.media", "bongacams.mobi",
  "bongacams.net", "bongacams.nl", "bongacams.org", "bongacams.quest",
  "bongacams.se", "bongacams.sex", "bongacams.sexy", "bongacams.tv",
  "bongacams.uk", "bongacams.video", "bongacams.xxx", "boyfriendtv.cloud",
  "boyfriendtv.co", "boyfriendtv.com", "boyfriendtv.fun", "boyfriendtv.icu",
  "boyfriendtv.im", "boyfriendtv.in", "boyfriendtv.info", "boyfriendtv.life",
  "boyfriendtv.me", "boyfriendtv.net", "boyfriendtv.one", "boyfriendtv.org",
  "boyfriendtv.porn", "boyfriendtv.pro", "boyfriendtv.sex", "boyfriendtv.video",
  "boyfriendtv.xxx", "brazzers.at", "brazzers.bg", "brazzers.cam",
  "brazzers.cl", "brazzers.com", "brazzers.cyou", "brazzers.desi",
  "brazzers.dk", "brazzers.fr", "brazzers.gay", "brazzers.house",
  "brazzers.io", "brazzers.it", "brazzers.kim", "brazzers.life",
  "brazzers.me", "brazzers.mobi", "brazzers.net", "brazzers.nu",
  "brazzers.org", "brazzers.red", "brazzers.rocks", "brazzers.srl",
  "brazzers.studio", "brazzers.su", "brazzers.today", "brazzers.tube",
  "brazzers.us", "brazzers.webcam", "brazzers.ws", "brazzers.wtf",
  "brazzers.xxx", "cam4.am", "cam4.bo", "cam4.ca",
  "cam4.cash", "cam4.coach", "cam4.com", "cam4.de",
  "cam4.dk", "cam4.ec", "cam4.email", "cam4.es",
  "cam4.eu", "cam4.fi", "cam4.fr", "cam4.gt",
  "cam4.icu", "cam4.ie", "cam4.it", "cam4.llc",
  "cam4.love", "cam4.money", "cam4.mx", "cam4.ng",
  "cam4.nl", "cam4.no", "cam4.nu", "cam4.one",
  "cam4.org", "cam4.pa", "cam4.pl", "cam4.porn",
  "cam4.pt", "cam4.ryukyu", "cam4.to", "cam4.tw",
  "cam4.xxx", "camsoda.ai", "camsoda.app", "camsoda.co",
  "camsoda.com", "camsoda.me", "camsoda.mobi", "camsoda.sex",
  "camsoda.tv", "camsoda.webcam", "chaturbate.adult", "chaturbate.asia",
  "chaturbate.be", "chaturbate.bet", "chaturbate.ca", "chaturbate.cam",
  "chaturbate.camera", "chaturbate.center", "chaturbate.cl", "chaturbate.co",
  "chaturbate.com", "chaturbate.cz", "chaturbate.dating", "chaturbate.deals",
  "chaturbate.eu", "chaturbate.fit", "chaturbate.free", "chaturbate.global",
  "chaturbate.id", "chaturbate.im", "chaturbate.lol", "chaturbate.lt",
  "chaturbate.ltd", "chaturbate.lu", "chaturbate.lv", "chaturbate.md",
  "chaturbate.me", "chaturbate.mobi", "chaturbate.moda", "chaturbate.net",
  "chaturbate.nl", "chaturbate.no", "chaturbate.onl", "chaturbate.online",
  "chaturbate.org", "chaturbate.page", "chaturbate.ph", "chaturbate.pro",
  "chaturbate.ro", "chaturbate.sex", "chaturbate.su", "chaturbate.sx",
  "chaturbate.today", "chaturbate.tv", "chaturbate.us", "chaturbate.video",
  "chaturbate.watch", "crazyshit.com", "drtuber.asia", "drtuber.com",
  "drtuber.desi", "drtuber.mobi", "drtuber.su", "drtuber.us",
  "efukt.com", "efukt.me", "efukt.tv", "eporner.app",
  "eporner.asia", "eporner.bid", "eporner.blog", "eporner.buzz",
  "eporner.casa", "eporner.cfd", "eporner.cloud", "eporner.co",
  "eporner.com", "eporner.dev", "eporner.es", "eporner.fun",
  "eporner.gold", "eporner.gr", "eporner.guru", "eporner.horse",
  "eporner.hu", "eporner.icu", "eporner.id", "eporner.in",
  "eporner.info", "eporner.it", "eporner.life", "eporner.live",
  "eporner.me", "eporner.mobi", "eporner.mobile", "eporner.name",
  "eporner.nl", "eporner.now", "eporner.party", "eporner.pink",
  "eporner.pl", "eporner.pro", "eporner.quest", "eporner.ru",
  "eporner.run", "eporner.sex", "eporner.space", "eporner.stream",
  "eporner.tel", "eporner.today", "eporner.us", "eporner.video",
  "eporner.win", "eporner.work", "eporner.xxx", "erome.ac",
  "erome.casa", "erome.com", "erome.fan", "erome.io",
  "erome.it", "erome.me", "erome.nl", "erome.tv",
  "erome.wtf", "extremetube.com", "extremetube.dk", "fapdu.com",
  "fapdu.video", "fapello.boo", "fapello.com", "fapello.de",
  "fapello.fans", "fapello.fr", "fapello.is", "fapello.lol",
  "fapello.ru", "fapello.su", "fapello.to", "fapello.tv",
  "fapello.video", "fapello.xxx", "freeones.am", "freeones.at",
  "freeones.be", "freeones.ca", "freeones.ch", "freeones.chat",
  "freeones.com", "freeones.cz", "freeones.dk", "freeones.es",
  "freeones.eu", "freeones.fi", "freeones.fm", "freeones.fr",
  "freeones.gr", "freeones.im", "freeones.info", "freeones.it",
  "freeones.jp", "freeones.live", "freeones.nl", "freeones.pl",
  "freeones.pt", "freeones.ro", "freeones.ru", "freeones.se",
  "freeones.sk", "freeones.tm", "freeones.tv", "freeones.vg",
  "freeones.world", "freeones.ws", "fuq.bet", "fuq.com",
  "fuq.hu", "fuq.kim", "fuq.mom", "fuq.nl",
  "fuq.one", "fuq.onl", "fuq.today", "gotporn.co",
  "gotporn.com", "gotporn.hu", "gotporn.info", "gotporn.mobi",
  "gotporn.online", "gotporn.pro", "gotporn.su", "gotporn.tel",
  "gotporn.yachts", "hanime.boo", "hanime.com", "hanime.fun",
  "hanime.me", "hanime.mobi", "hanime.net", "hanime.red",
  "hanime.stream", "hanime.tv", "hanime.uk", "hanime.watch",
  "hanime.xxx", "hclips.cfd", "hclips.com", "hclips.de",
  "hclips.me", "hclips.net", "hclips.online", "hclips.pro",
  "hentaihaven.app", "hentaihaven.co", "hentaihaven.com", "hentaihaven.fun",
  "hentaihaven.icu", "hentaihaven.io", "hentaihaven.li", "hentaihaven.me",
  "hentaihaven.net", "hentaihaven.online", "hentaihaven.org", "hentaihaven.red",
  "hentaihaven.ws", "hentaihaven.xxx", "hqporner.at", "hqporner.bid",
  "hqporner.bond", "hqporner.com", "hqporner.de", "hqporner.gg",
  "hqporner.hu", "hqporner.in", "hqporner.info", "hqporner.nl",
  "hqporner.plus", "hqporner.red", "hqporner.rocks", "hqporner.ru",
  "hqporner.sex", "hqporner.su", "hqporner.us", "ixxx.asia",
  "ixxx.at", "ixxx.bid", "ixxx.cam", "ixxx.cloud",
  "ixxx.com", "ixxx.es", "ixxx.fit", "ixxx.fr",
  "ixxx.fun", "ixxx.gg", "ixxx.gold", "ixxx.homes",
  "ixxx.hu", "ixxx.in", "ixxx.ink", "ixxx.link",
  "ixxx.live", "ixxx.mom", "ixxx.nl", "ixxx.one",
  "ixxx.onl", "ixxx.party", "ixxx.plus", "ixxx.pro",
  "ixxx.pt", "ixxx.red", "ixxx.rest", "ixxx.rocks",
  "ixxx.ru", "ixxx.run", "ixxx.se", "ixxx.sex",
  "ixxx.si", "ixxx.su", "ixxx.today", "ixxx.video",
  "ixxx.watch", "ixxx.webcam", "ixxx.win", "ixxx.world",
  "ixxx.wtf", "ixxx.yachts", "javfree.asia", "javfree.com",
  "javfree.la", "javfree.me", "javfree.org", "javfree.sh",
  "javhd.ai", "javhd.baby", "javhd.best", "javhd.bid",
  "javhd.bio", "javhd.build", "javhd.co", "javhd.com",
  "javhd.fit", "javhd.global", "javhd.group", "javhd.hot",
  "javhd.icu", "javhd.im", "javhd.info", "javhd.life",
  "javhd.live", "javhd.lol", "javhd.men", "javhd.moe",
  "javhd.mov", "javhd.mx", "javhd.name", "javhd.net",
  "javhd.news", "javhd.ninja", "javhd.one", "javhd.onl",
  "javhd.page", "javhd.pro", "javhd.rocks", "javhd.sh",
  "javhd.space", "javhd.tax", "javhd.to", "javhd.today",
  "javhd.tube", "javhd.video", "javhd.watch", "javhd.ws",
  "javhd.yachts", "keezmovies.com", "keezmovies.mobi", "keezmovies.online",
  "keezmovies.pro", "keezmovies.pw", "keezmovies.surf", "keezmovies.yachts",
  "livejasmin.cam", "livejasmin.chat", "livejasmin.cl", "livejasmin.com",
  "livejasmin.ec", "livejasmin.es", "livejasmin.fr", "livejasmin.hu",
  "livejasmin.icu", "livejasmin.io", "livejasmin.mn", "livejasmin.net",
  "livejasmin.pl", "livejasmin.porn", "livejasmin.sex", "livejasmin.show",
  "livejasmin.st", "livejasmin.tv", "livejasmin.vg", "livejasmin.xxx",
  "luxuretv.com", "luxuretv.fun", "missav.ai", "missav.app",
  "missav.bar", "missav.blog", "missav.cam", "missav.casa",
  "missav.chat", "missav.cloud", "missav.com", "missav.eu",
  "missav.fans", "missav.guide", "missav.hot", "missav.li",
  "missav.live", "missav.media", "missav.movie", "missav.nl",
  "missav.one", "missav.run", "missav.stream", "missav.to",
  "missav.uno", "missav.vin", "missav.ws", "missav.xxx",
  "motherless.co", "motherless.hu", "motherless.me", "motherless.pro",
  "motherless.tv", "motherless.yachts", "myfreecams.com", "myfreecams.de",
  "myfreecams.info", "myfreecams.nl", "myfreecams.org", "myfreecams.ru",
  "myfreecams.social", "nhentai.app", "nhentai.blog", "nhentai.com",
  "nhentai.gay", "nhentai.io", "nhentai.lol", "nhentai.name",
  "nhentai.net", "nhentai.one", "nhentai.org", "nhentai.stream",
  "nhentai.to", "nhentai.uk", "nhentai.wtf", "nhentai.xxx",
  "noodlemagazine.cam", "noodlemagazine.com", "noodlemagazine.gay", "noodlemagazine.guru",
  "noodlemagazine.homes", "noodlemagazine.life", "noodlemagazine.net", "noodlemagazine.plus",
  "noodlemagazine.run", "noodlemagazine.today", "noodlemagazine.tv", "onlyfans.com",
  "onlyfans.tv", "porn300.asia", "porn300.best", "porn300.blog",
  "porn300.casa", "porn300.cfd", "porn300.com", "porn300.fr",
  "porn300.icu", "porn300.in", "porn300.mom", "porn300.net",
  "porn300.online", "porn300.pro", "porn300.store", "porn300.su",
  "porn300.work", "porn300.world", "porn300.yachts", "porn7.info",
  "porn7.me", "porn7.net", "porn7.xxx", "pornbox.com",
  "pornbox.info", "pornbox.ink", "pornbox.live", "pornbox.one",
  "pornbox.org", "pornbox.ru", "pornbox.video", "pornbox.xxx",
  "porndig.chat", "porndig.com", "porndig.de", "porndig.live",
  "porndig.me", "porndig.mobi", "porndig.pro", "porndig.show",
  "porndig.us", "porndig.video", "pornhub.agency", "pornhub.alsace",
  "pornhub.am", "pornhub.app", "pornhub.at", "pornhub.band",
  "pornhub.bar", "pornhub.beer", "pornhub.best", "pornhub.bet",
  "pornhub.bg", "pornhub.bio", "pornhub.black", "pornhub.blog",
  "pornhub.bz", "pornhub.ca", "pornhub.cafe", "pornhub.care",
  "pornhub.cash", "pornhub.cf", "pornhub.ch", "pornhub.cl",
  "pornhub.cloud", "pornhub.cm", "pornhub.co", "pornhub.coach",
  "pornhub.codes", "pornhub.com", "pornhub.cool", "pornhub.cyou",
  "pornhub.cz", "pornhub.direct", "pornhub.dog", "pornhub.es",
  "pornhub.estate", "pornhub.fm", "pornhub.forum", "pornhub.fr",
  "pornhub.free", "pornhub.fyi", "pornhub.ga", "pornhub.games",
  "pornhub.global", "pornhub.gold", "pornhub.golf", "pornhub.gq",
  "pornhub.hk", "pornhub.hot", "pornhub.house", "pornhub.hu",
  "pornhub.it", "pornhub.kim", "pornhub.la", "pornhub.land",
  "pornhub.live", "pornhub.london", "pornhub.lu", "pornhub.me",
  "pornhub.men", "pornhub.mobi", "pornhub.mom", "pornhub.mov",
  "pornhub.mx", "pornhub.name", "pornhub.net", "pornhub.nl",
  "pornhub.nu", "pornhub.onl", "pornhub.online", "pornhub.org",
  "pornhub.pet", "pornhub.photos", "pornhub.pink", "pornhub.pl",
  "pornhub.place", "pornhub.plus", "pornhub.press", "pornhub.pro",
  "pornhub.promo", "pornhub.pt", "pornhub.pub", "pornhub.pw",
  "pornhub.red", "pornhub.ro", "pornhub.rocks", "pornhub.rodeo",
  "pornhub.rs", "pornhub.ru", "pornhub.run", "pornhub.sexy",
  "pornhub.so", "pornhub.social", "pornhub.sx", "pornhub.tc",
  "pornhub.team", "pornhub.tel", "pornhub.tg", "pornhub.tube",
  "pornhub.tv", "pornhub.tw", "pornhub.uk", "pornhub.vet",
  "pornhub.vg", "pornhub.video", "pornhub.vin", "pornhub.vu",
  "pornhub.watch", "pornhub.webcam", "pornhub.work", "pornhub.works",
  "pornhub.wtf", "pornhub.xxx", "pornhub.zone", "pornktube.com",
  "pornktube.de", "pornktube.porn", "pornktube.st", "pornktube.tv",
  "pornmd.co", "pornmd.com", "pornmd.hu", "pornmd.info",
  "pornmd.name", "pornmd.net", "pornmd.online", "pornmd.pro",
  "pornmd.yachts", "pornone.co", "pornone.com", "pornone.de",
  "pornone.fr", "pornone.info", "pornone.io", "pornone.live",
  "pornone.nl", "pornone.onl", "pornone.org", "pornone.party",
  "pornone.plus", "pornone.us", "porntrex.best", "porntrex.cloud",
  "porntrex.com", "porntrex.fr", "porntrex.gold", "porntrex.hu",
  "porntrex.in", "porntrex.info", "porntrex.io", "porntrex.it",
  "porntrex.party", "porntrex.pl", "porntrex.porn", "porntrex.skin",
  "porntrex.space", "porntrex.tech", "porntrex.tv", "porntrex.video",
  "porntrex.world", "porntrex.yachts", "redgifs.ai", "redgifs.cam",
  "redgifs.com", "redtube.adult", "redtube.ag", "redtube.ai",
  "redtube.am", "redtube.as", "redtube.asia", "redtube.at",
  "redtube.az", "redtube.ba", "redtube.bg", "redtube.bi",
  "redtube.bike", "redtube.blog", "redtube.blue", "redtube.bo",
  "redtube.bs", "redtube.by", "redtube.bz", "redtube.ca",
  "redtube.cam", "redtube.cd", "redtube.center", "redtube.ch",
  "redtube.co", "redtube.com", "redtube.cool", "redtube.cr",
  "redtube.cyou", "redtube.cz", "redtube.de", "redtube.direct",
  "redtube.dj", "redtube.ec", "redtube.es", "redtube.estate",
  "redtube.eu", "redtube.expert", "redtube.fm", "redtube.fr",
  "redtube.free", "redtube.fyi", "redtube.gg", "redtube.gl",
  "redtube.gp", "redtube.hk", "redtube.hn", "redtube.host",
  "redtube.hot", "redtube.hu", "redtube.icu", "redtube.im",
  "redtube.in", "redtube.info", "redtube.ink", "redtube.io",
  "redtube.is", "redtube.it", "redtube.je", "redtube.jp",
  "redtube.kg", "redtube.kim", "redtube.kr", "redtube.la",
  "redtube.ltd", "redtube.lu", "redtube.ly", "redtube.ma",
  "redtube.md", "redtube.me", "redtube.mk", "redtube.mobi",
  "redtube.movie", "redtube.ms", "redtube.mu", "redtube.mx",
  "redtube.my", "redtube.name", "redtube.net", "redtube.ninja",
  "redtube.onl", "redtube.org", "redtube.party", "redtube.pe",
  "redtube.ph", "redtube.photos", "redtube.pl", "redtube.pm",
  "redtube.porn", "redtube.pro", "redtube.pw", "redtube.re",
  "redtube.report", "redtube.rs", "redtube.ru", "redtube.sale",
  "redtube.sc", "redtube.se", "redtube.sex", "redtube.si",
  "redtube.sn", "redtube.so", "redtube.social", "redtube.td",
  "redtube.tj", "redtube.to", "redtube.tv", "redtube.tw",
  "redtube.uk", "redtube.us", "redtube.uz", "redtube.vc",
  "redtube.vet", "redtube.vg", "redtube.vin", "redtube.vn",
  "redtube.watch", "redtube.wtf", "redtube.xxx", "redtube.zone",
  "rule34.app", "rule34.art", "rule34.asia", "rule34.co",
  "rule34.com", "rule34.dev", "rule34.ee", "rule34.gg",
  "rule34.im", "rule34.ink", "rule34.kim", "rule34.lol",
  "rule34.moe", "rule34.my", "rule34.net", "rule34.one",
  "rule34.org", "rule34.porn", "rule34.pw", "rule34.si",
  "rule34.studio", "rule34.to", "rule34.tube", "rule34.us",
  "rule34.wtf", "rule34.xxx", "rule34.zone", "spankbang.com",
  "spankbang.de", "spankbang.fr", "spankbang.fun", "spankbang.gg",
  "spankbang.hu", "spankbang.live", "spankbang.name", "spankbang.org",
  "spankbang.party", "spankbang.pl", "spankbang.porn", "spankbang.red",
  "spankbang.rocks", "spankbang.run", "spankbang.show", "spankbang.video",
  "spankbang.win", "spankbang.xxx", "spankwire.com", "spankwire.works",
  "spankwire.world", "streamate.be", "streamate.cam", "streamate.co",
  "streamate.com", "streamate.es", "streamate.eu", "streamate.in",
  "streamate.ltd", "streamate.net", "streamate.no", "streamate.org",
  "streamate.sk", "streamate.tv", "streamate.xxx", "stripchat.adult",
  "stripchat.app", "stripchat.art", "stripchat.be", "stripchat.best",
  "stripchat.cam", "stripchat.care", "stripchat.co", "stripchat.com",
  "stripchat.direct", "stripchat.dk", "stripchat.eu", "stripchat.fans",
  "stripchat.fit", "stripchat.global", "stripchat.lgbt", "stripchat.life",
  "stripchat.me", "stripchat.men", "stripchat.mx", "stripchat.nl",
  "stripchat.ooo", "stripchat.org", "stripchat.pl", "stripchat.porn",
  "stripchat.pw", "stripchat.red", "stripchat.run", "stripchat.studio",
  "stripchat.tel", "stripchat.uk", "stripchat.us", "stripchat.vision",
  "stripchat.webcam", "sunporno.asia", "sunporno.cam", "sunporno.com",
  "sunporno.me", "sxyprn.com", "sxyprn.fun", "sxyprn.gay",
  "sxyprn.hu", "sxyprn.icu", "sxyprn.info", "sxyprn.mobi",
  "sxyprn.net", "sxyprn.pro", "sxyprn.work", "thisvid.asia",
  "thisvid.com", "thisvid.io", "thisvid.online", "thisvid.yachts",
  "thumbzilla.casa", "thumbzilla.com", "thumbzilla.hu", "thumbzilla.me",
  "thumbzilla.net", "thumbzilla.nl", "thumbzilla.org", "thumbzilla.pro",
  "thumbzilla.work", "thumbzilla.xxx", "tktube.com", "tktube.ru",
  "tktube.to", "tnaflix.asia", "tnaflix.bid", "tnaflix.bond",
  "tnaflix.com", "tnaflix.gay", "tnaflix.pro", "tnaflix.us",
  "tnaflix.world", "tnaflix.yachts", "tube8.asia", "tube8.at",
  "tube8.best", "tube8.bg", "tube8.blue", "tube8.ca",
  "tube8.cam", "tube8.cloud", "tube8.co", "tube8.com",
  "tube8.cool", "tube8.es", "tube8.fr", "tube8.fun",
  "tube8.guru", "tube8.hu", "tube8.info", "tube8.ink",
  "tube8.it", "tube8.link", "tube8.lol", "tube8.mobi",
  "tube8.my", "tube8.net", "tube8.ninja", "tube8.org",
  "tube8.pink", "tube8.pro", "tube8.pt", "tube8.rocks",
  "tube8.run", "tube8.su", "tube8.to", "tube8.today",
  "tube8.tube", "tube8.vc", "tube8.work", "tube8.wtf",
  "tube8.xxx", "tubegalore.asia", "tubegalore.band", "tubegalore.buzz",
  "tubegalore.cm", "tubegalore.com", "tubegalore.de", "tubegalore.hu",
  "tubegalore.info", "tubegalore.life", "tubegalore.mom", "tubegalore.nl",
  "tubegalore.online", "tubegalore.pro", "tubegalore.stream", "tubegalore.tv",
  "tubegalore.video", "tubegalore.yachts", "txxx.asia", "txxx.bid",
  "txxx.casa", "txxx.com", "txxx.cz", "txxx.hu",
  "txxx.info", "txxx.ink", "txxx.me", "txxx.nl",
  "txxx.party", "txxx.pl", "txxx.porn", "txxx.pro",
  "txxx.store", "txxx.tube", "txxx.tv", "txxx.us",
  "txxx.video", "txxx.yachts", "upornia.bid", "upornia.com",
  "upornia.in", "upornia.info", "upornia.net", "upornia.online",
  "upornia.org", "upornia.trade", "upornia.tube", "vjav.com",
  "vjav.info", "vjav.ink", "vjav.me", "vjav.one",
  "vjav.tube", "watchmygf.com", "watchmygf.fun", "watchmygf.me",
  "watchmygf.mobi", "watchmygf.name", "watchmygf.net", "watchmygf.sex",
  "watchmygf.to", "watchmygf.webcam", "watchmygf.xxx", "xbabe.asia",
  "xbabe.casa", "xbabe.com", "xbabe.mobi", "xhamster.asia",
  "xhamster.autos", "xhamster.best", "xhamster.bid", "xhamster.cam",
  "xhamster.casa", "xhamster.co", "xhamster.coffee", "xhamster.com",
  "xhamster.cz", "xhamster.desi", "xhamster.dev", "xhamster.estate",
  "xhamster.eu", "xhamster.fan", "xhamster.fm", "xhamster.fr",
  "xhamster.gold", "xhamster.guru", "xhamster.hair", "xhamster.health",
  "xhamster.homes", "xhamster.host", "xhamster.how", "xhamster.hu",
  "xhamster.icu", "xhamster.id", "xhamster.in", "xhamster.la",
  "xhamster.lgbt", "xhamster.life", "xhamster.live", "xhamster.living",
  "xhamster.llc", "xhamster.loan", "xhamster.ltd", "xhamster.mobi",
  "xhamster.moe", "xhamster.mx", "xhamster.name", "xhamster.net",
  "xhamster.ninja", "xhamster.nl", "xhamster.nu", "xhamster.nyc",
  "xhamster.one", "xhamster.org", "xhamster.party", "xhamster.pink",
  "xhamster.plus", "xhamster.pt", "xhamster.quest", "xhamster.red",
  "xhamster.rent", "xhamster.rest", "xhamster.ro", "xhamster.run",
  "xhamster.sex", "xhamster.tax", "xhamster.tv", "xhamster.vg",
  "xhamster.world", "xhamster.ws", "xhamster.wtf", "xhamster.xxx",
  "xhamster.yachts", "xmoviesforyou.com", "xmoviesforyou.video", "xnxx.ac",
  "xnxx.actor", "xnxx.adult", "xnxx.ae", "xnxx.ag",
  "xnxx.ai", "xnxx.al", "xnxx.am", "xnxx.army",
  "xnxx.asia", "xnxx.at", "xnxx.band", "xnxx.bar",
  "xnxx.be", "xnxx.best", "xnxx.bet", "xnxx.blue",
  "xnxx.boats", "xnxx.bz", "xnxx.ca", "xnxx.cab",
  "xnxx.cafe", "xnxx.cam", "xnxx.care", "xnxx.cash",
  "xnxx.cd", "xnxx.center", "xnxx.ch", "xnxx.chat",
  "xnxx.cheap", "xnxx.city", "xnxx.cl", "xnxx.cm",
  "xnxx.co", "xnxx.coach", "xnxx.com", "xnxx.cr",
  "xnxx.cx", "xnxx.cyou", "xnxx.cz", "xnxx.de",
  "xnxx.dev", "xnxx.dj", "xnxx.dk", "xnxx.dog",
  "xnxx.ec", "xnxx.ee", "xnxx.es", "xnxx.eu",
  "xnxx.events", "xnxx.fail", "xnxx.fi", "xnxx.fit",
  "xnxx.forex", "xnxx.forum", "xnxx.fr", "xnxx.fun",
  "xnxx.gd", "xnxx.gg", "xnxx.gift", "xnxx.giving",
  "xnxx.gl", "xnxx.gold", "xnxx.gr", "xnxx.green",
  "xnxx.group", "xnxx.gs", "xnxx.gt", "xnxx.gy",
  "xnxx.haus", "xnxx.health", "xnxx.hk", "xnxx.hm",
  "xnxx.hn", "xnxx.horse", "xnxx.host", "xnxx.hu",
  "xnxx.ie", "xnxx.im", "xnxx.ink", "xnxx.io",
  "xnxx.irish", "xnxx.is", "xnxx.je", "xnxx.jp",
  "xnxx.kaufen", "xnxx.kim", "xnxx.kr", "xnxx.la",
  "xnxx.lc", "xnxx.lgbt", "xnxx.li", "xnxx.llc",
  "xnxx.locker", "xnxx.lol", "xnxx.london", "xnxx.lu",
  "xnxx.luxe", "xnxx.lv", "xnxx.mba", "xnxx.me",
  "xnxx.mk", "xnxx.mn", "xnxx.moda", "xnxx.money",
  "xnxx.ms", "xnxx.name", "xnxx.net", "xnxx.ninja",
  "xnxx.no", "xnxx.now", "xnxx.nu", "xnxx.org",
  "xnxx.party", "xnxx.pe", "xnxx.pet", "xnxx.ph",
  "xnxx.pink", "xnxx.pizza", "xnxx.pl", "xnxx.place",
  "xnxx.plus", "xnxx.porn", "xnxx.press", "xnxx.pro",
  "xnxx.pt", "xnxx.pub", "xnxx.qpon", "xnxx.quest",
  "xnxx.re", "xnxx.red", "xnxx.reisen", "xnxx.report",
  "xnxx.rest", "xnxx.rodeo", "xnxx.rs", "xnxx.run",
  "xnxx.sale", "xnxx.sc", "xnxx.sex", "xnxx.sg",
  "xnxx.sh", "xnxx.si", "xnxx.sk", "xnxx.so",
  "xnxx.solar", "xnxx.st", "xnxx.studio", "xnxx.su",
  "xnxx.sx", "xnxx.tattoo", "xnxx.taxi", "xnxx.team",
  "xnxx.tips", "xnxx.to", "xnxx.today", "xnxx.town",
  "xnxx.tv", "xnxx.us", "xnxx.uz", "xnxx.video",
  "xnxx.vu", "xnxx.wales", "xnxx.wang", "xnxx.watch",
  "xnxx.wf", "xnxx.works", "xnxx.world", "xnxx.ws",
  "xnxx.xxx", "xnxx.yt", "xtube.asia", "xtube.casa",
  "xtube.co", "xtube.com", "xtube.de", "xtube.org",
  "xtube.pro", "xtube.run", "xtube.su", "xtube.tech",
  "xtube.tel", "xtube.wtf", "xtube.xxx", "xvideos.ac",
  "xvideos.adult", "xvideos.ai", "xvideos.am", "xvideos.as",
  "xvideos.at", "xvideos.be", "xvideos.black", "xvideos.blog",
  "xvideos.bo", "xvideos.boston", "xvideos.bz", "xvideos.ca",
  "xvideos.cafe", "xvideos.casa", "xvideos.cd", "xvideos.ch",
  "xvideos.city", "xvideos.cl", "xvideos.clinic", "xvideos.cm",
  "xvideos.cn", "xvideos.co", "xvideos.com", "xvideos.cr",
  "xvideos.cz", "xvideos.dad", "xvideos.de", "xvideos.dk",
  "xvideos.do", "xvideos.ee", "xvideos.email", "xvideos.es",
  "xvideos.fan", "xvideos.fm", "xvideos.fr", "xvideos.fyi",
  "xvideos.garden", "xvideos.gl", "xvideos.golf", "xvideos.gp",
  "xvideos.gr", "xvideos.gratis", "xvideos.gy", "xvideos.health",
  "xvideos.hk", "xvideos.hn", "xvideos.hr", "xvideos.ht",
  "xvideos.hu", "xvideos.id", "xvideos.im", "xvideos.immo",
  "xvideos.in", "xvideos.irish", "xvideos.is", "xvideos.it",
  "xvideos.je", "xvideos.jp", "xvideos.kr", "xvideos.la",
  "xvideos.lc", "xvideos.llc", "xvideos.lu", "xvideos.lv",
  "xvideos.me", "xvideos.mg", "xvideos.miami", "xvideos.mk",
  "xvideos.moda", "xvideos.mom", "xvideos.money", "xvideos.movie",
  "xvideos.mu", "xvideos.mx", "xvideos.name", "xvideos.net",
  "xvideos.news", "xvideos.nl", "xvideos.no", "xvideos.nu",
  "xvideos.one", "xvideos.onl", "xvideos.online", "xvideos.org",
  "xvideos.page", "xvideos.party", "xvideos.ph", "xvideos.photos",
  "xvideos.pl", "xvideos.porn", "xvideos.pt", "xvideos.re",
  "xvideos.red", "xvideos.rest", "xvideos.ro", "xvideos.rs",
  "xvideos.rsvp", "xvideos.ru", "xvideos.se", "xvideos.sex",
  "xvideos.sh", "xvideos.show", "xvideos.si", "xvideos.skin",
  "xvideos.so", "xvideos.st", "xvideos.su", "xvideos.surf",
  "xvideos.sv", "xvideos.sx", "xvideos.tf", "xvideos.tienda",
  "xvideos.tl", "xvideos.tube", "xvideos.tv", "xvideos.uk",
  "xvideos.uno", "xvideos.us", "xvideos.uy", "xvideos.vc",
  "xvideos.vin", "xvideos.wales", "xvideos.xxx", "xvideos.yt",
  "xvideos2.asia", "xvideos2.com", "xvideos2.fun", "xvideos2.pro",
  "xvideos2.su", "xvideos2.uk", "xxxbunker.com", "xxxbunker.mobi",
  "xxxbunker.org", "xxxbunker.ru", "xxxvideos.bid", "xxxvideos.blog",
  "xxxvideos.bond", "xxxvideos.casa", "xxxvideos.com", "xxxvideos.cz",
  "xxxvideos.fans", "xxxvideos.ink", "xxxvideos.kim", "xxxvideos.name",
  "xxxvideos.one", "xxxvideos.ovh", "xxxvideos.pro", "xxxvideos.red",
  "xxxvideos.ru", "xxxvideos.run", "xxxvideos.sexy", "xxxvideos.su",
  "xxxvideos.xxx", "youporn.ai", "youporn.app", "youporn.asia",
  "youporn.bg", "youporn.bid", "youporn.bike", "youporn.cam",
  "youporn.ch", "youporn.com", "youporn.cyou", "youporn.dating",
  "youporn.day", "youporn.eu", "youporn.expert", "youporn.fm",
  "youporn.guru", "youporn.hu", "youporn.icu", "youporn.ink",
  "youporn.it", "youporn.kim", "youporn.ltd", "youporn.miami",
  "youporn.mn", "youporn.mobi", "youporn.movie", "youporn.name",
  "youporn.ninja", "youporn.nu", "youporn.one", "youporn.plus",
  "youporn.pro", "youporn.pt", "youporn.pub", "youporn.red",
  "youporn.run", "youporn.se", "youporn.sexy", "youporn.so",
  "youporn.tel", "youporn.tg", "youporn.today", "youporn.tube",
  "youporn.tv", "youporn.uk", "youporn.uno", "youporn.watch",
  "youporn.works", "youporn.world", "youporn.ws", "youporn.wtf",
  "youporn.xxx", "youporn.zone", "zbporn.com", "zbporn.de",
  "zbporn.net", "zbporn.tv"
];

const ADULT_RULE_ID_START = 100;

function buildAdultRules(adult) {
  if (!adult.master) return [];

  return ADULT_DOMAINS.map((domain, i) => ({
    id: ADULT_RULE_ID_START + i,
    priority: 1,
    action: {
      type: "redirect",
      redirect: { extensionPath: `/blocked.html?cat=adult&site=${encodeURIComponent(domain)}` }
    },
    condition: {
      urlFilter: `||${domain}^`,
      resourceTypes: ["main_frame"]
    }
  }));
}

async function applyRules(settings) {
  const newRules = buildAdultRules(settings.adult);

  const existing = await chrome.declarativeNetRequest.getDynamicRules();
  const removeRuleIds = existing.map((r) => r.id);

  await chrome.declarativeNetRequest.updateDynamicRules({
    removeRuleIds,
    addRules: newRules
  });
}

async function getSettings() {
  const stored = await chrome.storage.local.get("settings");
  if (stored.settings) return stored.settings;
  await chrome.storage.local.set({ settings: DEFAULT_SETTINGS });
  return DEFAULT_SETTINGS;
}

chrome.runtime.onInstalled.addListener(async () => {
  const settings = await getSettings();
  await applyRules(settings);
});

chrome.runtime.onStartup.addListener(async () => {
  const settings = await getSettings();
  await applyRules(settings);
});

chrome.storage.onChanged.addListener(async (changes, area) => {
  if (area === "local" && changes.settings) {
    await applyRules(changes.settings.newValue);
  }
});
